#############################################
##              Network Tokens             ##
##                By: xTDKx                ##
#############################################

# Network Tokens config

Database Address: localhost
Database Port: 3306
Database Name: NetworkTokens
Database User: mc1
Database Password: mc1pass
Table Prefix: nt_

# How often Network Tokens checks and saves changes to the database. (Seconds)
Sync Interval: 10

# If enabled, you will be notified of new updates via the server console.
Check Updates: true

# The amount of Network Tokens a player gets the first time they join the server.
Initial Amount: 0